# Generated by Django 4.2 on 2023-05-22 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name="Yo'nalish nomi")),
                ('language', models.CharField(choices=[("O'zbek", "O'zbek"), ('Rus', 'Rus'), ('Boshqa', 'Boshqa')], max_length=10, verbose_name="Ta'lim tili")),
                ('study_form', models.CharField(choices=[('Kunduzgi', 'Kunduzgi'), ('Kechki', 'Kechki'), ('Sirtqi', 'Sirtqi')], max_length=10, verbose_name="Ta'lim shakli")),
                ('code', models.CharField(blank=True, max_length=30, null=True, verbose_name="Yo'nalish kodi")),
                ('year', models.IntegerField(verbose_name='Qabul qilingan yili')),
                ('semester_number', models.IntegerField(default=8, verbose_name='Semestr soni')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.faculty', verbose_name='Fakulteti')),
            ],
            options={
                'verbose_name': "Yo'nalish",
                'verbose_name_plural': "2. Barcha yo'nalishlar",
            },
        ),
    ]
