# Generated by Django 4.2 on 2023-05-22 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_direction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direction',
            options={'verbose_name': "Yo'nalish", 'verbose_name_plural': "4. Barcha yo'nalishlar"},
        ),
        migrations.RemoveField(
            model_name='direction',
            name='semester_number',
        ),
        migrations.AlterField(
            model_name='direction',
            name='study_form',
            field=models.CharField(choices=[('Kunduzgi', 'Kunduzgi'), ('Kechki', 'Kechki'), ('Sirtqi', 'Sirtqi')], max_length=15, verbose_name="Ta'lim shakli"),
        ),
        migrations.CreateModel(
            name='SmallGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Guruh nomi')),
                ('sum_students', models.IntegerField(default=0)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.direction', verbose_name="Yo'nalishi")),
            ],
            options={
                'verbose_name': 'Guruh',
                'verbose_name_plural': '5. Guruhlar',
            },
        ),
    ]
