# Generated by Django 4.2 on 2023-05-22 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_alter_direction_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SmallGroup',
        ),
    ]
