# Generated by Django 4.2 on 2023-05-22 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0005_smallgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScienceWithSemestr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestr', models.IntegerField(verbose_name='Semestr raqami')),
                ('science_code', models.CharField(max_length=150, verbose_name='Fan kodi')),
                ('exam', models.CharField(choices=[('Imtihon', 'Imtihon'), ('Sinov', 'Sinov')], max_length=10, verbose_name='Imtihon shakli')),
                ('credit', models.IntegerField(verbose_name='Kredit miqdori')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.direction')),
                ('science', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.science')),
            ],
            options={
                'verbose_name': 'Fan rejasi',
                'verbose_name_plural': '6. Semestrlik fanlar',
            },
        ),
    ]
