# Generated by Django 4.2 on 2023-05-23 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curriculum', '0006_sciencewithsemestr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cafedra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.cafedra', verbose_name='Kafedrasi')),
                ('sciences', models.ManyToManyField(to='curriculum.science', verbose_name='Fanlar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "O'qituvchi",
                'verbose_name_plural': "7. O'qituvchilar",
            },
        ),
    ]
