# Generated by Django 4.2 on 2023-05-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0007_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='sciences',
            field=models.ManyToManyField(related_name='sciences', related_query_name='sciences', to='curriculum.science', verbose_name='Fanlar'),
        ),
    ]
