# Generated by Django 4.2 on 2023-05-23 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0008_alter_teacher_sciences'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonWithTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_type', models.CharField(choices=[('Amaliyot', 'Amaliyot'), ("Ma'ruza", "Ma'ruza"), ('Seminar', 'Seminar'), ('Labaratoriya', 'Labaratoriya'), ("Mustaqil ta'lim", "Mustaqil ta'lim"), ('Kurs ishi', 'Kurs ishi')], max_length=20, verbose_name='Dars turi')),
                ('time', models.IntegerField(verbose_name='Dars soati')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.smallgroup', verbose_name='Guruh')),
                ('science', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.sciencewithsemestr', verbose_name='Fan')),
                ('teacher', models.ManyToManyField(to='curriculum.teacher', verbose_name="Dars beruvchi o'qituvchilar")),
            ],
            options={
                'verbose_name': 'Dars',
                'verbose_name_plural': '8. Darslar',
            },
        ),
    ]
