# Generated by Django 4.2 on 2023-05-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0010_alter_lessonwithteacher_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonwithteacher',
            name='teacher',
            field=models.ManyToManyField(blank=True, to='curriculum.teacher', verbose_name="Dars beruvchi o'qituvchilar"),
        ),
    ]
