# Generated by Django 4.2 on 2023-05-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0012_propractice_propracticewithgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonwithteacher',
            name='time',
        ),
        migrations.RemoveField(
            model_name='sciencewithsemestr',
            name='credit',
        ),
        migrations.AddField(
            model_name='sciencewithsemestr',
            name='course_work',
            field=models.BooleanField(default=False, verbose_name='Kurs ishi'),
        ),
        migrations.AddField(
            model_name='sciencewithsemestr',
            name='independent_work',
            field=models.IntegerField(default=0, verbose_name='Mustaqil ish'),
        ),
        migrations.AddField(
            model_name='sciencewithsemestr',
            name='laboratory',
            field=models.IntegerField(default=0, verbose_name='Labaratoriya'),
        ),
        migrations.AddField(
            model_name='sciencewithsemestr',
            name='lecture',
            field=models.IntegerField(default=0, verbose_name="Ma'ruza"),
        ),
        migrations.AddField(
            model_name='sciencewithsemestr',
            name='practice',
            field=models.IntegerField(default=0, verbose_name='Amaliyot'),
        ),
        migrations.AddField(
            model_name='sciencewithsemestr',
            name='seminar',
            field=models.IntegerField(default=0, verbose_name='Seminar'),
        ),
    ]
