# Generated by Django 4.2 on 2023-06-06 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0013_remove_lessonwithteacher_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smallgroup',
            name='name',
        ),
        migrations.AddField(
            model_name='smallgroup',
            name='number',
            field=models.IntegerField(default=0, verbose_name='Guruh raqami'),
        ),
    ]
