# Generated by Django 4.2 on 2023-06-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0014_remove_smallgroup_name_smallgroup_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sciencewithsemestr',
            name='credit',
            field=models.IntegerField(default=0, verbose_name='Kredit miqdori'),
        ),
    ]
